services: 
 app:
  build: ./python
  ports: 
      - "9000:9000"
  environment:
      - FRONT_URL=http://localhost:3000


 web:
   build: ./typescript/simple-mercari-web
   ports: 
      - "3000:3000"
   environment:
      - REACT_APP_API_URL=http://app:9000
   depends_on:
      - app